#counting number of nucleotides for DNA

from validateseq import validateseq
def countnuc(seq):
    seq=seq.replace("\n","")
    temp={"A":0,"C":0,"G":0,"T":0}
    for n in seq:
        temp[n] += 1
    print(temp["A"],temp["C"],temp["G"],temp["T"])

countnuc(validateseq("""GTCGAGGCGAGCGCCAGGATGGGTTACCGAGTGGCGGGCGAGGGAGAGTGGCGGTAGACCACCCGTAAGAGCCATCTTAGCACCAATGCCCTAGCTCAGTACCTGTTTACTCGTTTAGTTCAGCAGGTCTTCATAGTCAATCCGTGGCCGTCCATGGGACACGGGCCGAGCTGCCAACAGTATAAACCGTGCTTCGTGCCCGTCCATCTTTGGCACATCAACAACCGATTGCTTGCCCAAGGCCTGATAGCGGGGGGATTCTTAAAAAATGAATGGATGCGCGTCTGGCTACATTGGGTCAACTCGCGTGCCGGCTATCCATAAGTGGATCAATTACCTTTGCTCGACCTCTGGCTCGGCCCCCTCACTGGTACTGCAATCTATTAGTATTGCGACTATCTACCGGGAAAAACCTTTTATGGTATCCGGGTCCTTAGGTAGTGTAGGAGTGGACACGTTAAATGCTCGTCACTCCGTTGGTGCCTGCCAAACTGCCTCGCCTTAATTTGATAATACAGGATATAAGGTTGCAATCGCGTATCTCAATCGAAACATTCCAGGCCTTCGAACGAGATACCAGTGCGTTGCCCCCAAGTTCTGCATTTTTATATTGTTGCATACGAGAACCTCTCGTATGCTTCTTTCACCTCTAACACGTTCTACAAAGGACTTGCGCGGAGTCAATGTCTCAACGTTGTGCACTAGCATTCGTGGAGAAGCCAGACCGAGCGGGGGGAACTAGTCAGTGGAGAAGGGCGCAACGCAAAGTGCTCATAATTACTGATGAGCCTTGGAGGAGATTTAAGTGGTCTGCATGCGTATGCATTCAACTGTCCCGTTACGGAAGAAGCGATATCGATTC
"""))
