#reverse of a dna sequence
def dna_rev(dnaseq):
    seq={"A":"T","T":"A","G":"C","C":"G"}
    dnaseq=dnaseq.replace("\n","")
    rev_dna=''.join(seq[n] for n in dnaseq[::-1])    
    print(rev_dna)
dna_rev("""CAACCTGAGGTGTTCTGGACTCGAACGACATCCTGGCTCCGAACGAAGACTTAAGCATAACGGAGTATGTGTCGTATCTCGTCCAGACCATACGAAACTATCAGCCGGTAAACATCTTCGCAATACCTGTGCAACGGATTAAGCTTTTGAAGGGTTGTTAGCATTGAGTAGGCCCACTATGTCGGTGGTTGCAACATCACGGTCTCGTGGGAACCTCGGCAGGTGACCACAATCCTAACCAACCGTTTTCCGATCGGACACAGAGAGACGGTTAATCGATGGATACCTTCCGAACAATCCTCTTTGATGAGAACGCACAAGTGGCAAATCATCAAACAGCCGACCCTTCTTTCTGTTTCCAGCTAGGTTAGGCACTAGACTCAGTTCCGCGATTTCATGTCAAATCGGGTGTGCATTCCCGCACTGCTGTGATCGCCTTTAATAGTCGATAAACCTGTCACCCCTTTCCAGATAGTAGCAGGAGTGGATAGTCCCCTCTTATGTCACTCCCCGTGCTCGTAATAGTGCACGCTATACAGAAAACACTCAGTTGTAACCGTCTCGCATCTCATAATCATAACTTAAGTCTGACACTTCAGCCCGTCTAGCTCATTTTTATAGTCCGCGCCCGGTTTCATTACTCCCCTTTCAATTACGGTTAAAAGGGGGAGGAGAGAGGCACTCATTGACTTCAAAATGCCCGAATCACTGAAGAGCTATCGATCTTGACTATTCACTCACGTTTAAGCTATTTGGTAAATCCTATAAGCGATAAATGAATGAGCCTACCACTGCAGCACTTAGGGTGTATCATCGCCAGGTAACCCGATGCAGATGCGCTGCAAAAACTTTTGGCAGCCGAGCTAATCATAATCTTCACAACCGGATCCATACTTTTATA
""")
        
